---
output:
  html_document:
    toc: true
    toc_float: true
---


<link rel="stylesheet" href="styles.css" type="text/css" />

<br>

## Papers/Abstracts

***

## 2018

<i> Abstract: </i> **Candace Haghighi**, Bin Cheng, Jessica R. Starr, Jane B. Peters, Tirissa J. Reid, Michelle P. Warren, Gabrielle Page-Wilson. Clinical, Imaging, and Biochemical Parameters Favoring the Diagnosis of Cushing's Syndrome in Women Presenting With Suspected Polycystic Ovarian Syndrome (PCOS). ENDO 2018. [[Abstracts Online](http://www.abstractsonline.com/pp8/#!/4482/presentation/8188)] 

Richard G. James, Stephen R. Reeves, Kaitlyn A. Barrow, Maria P. White, Veronika A. Glukhova, **Candace Haghighi**, Dana Seyoum, and Jason S. Debley. Deficient Follistatin-like 3 Secretion by Asthmatic Airway Epithelium Impairs Fibroblast Regulation and Fibroblast-to-myofibroblast Transition. <i> American Journal of Respiratory Cell and Molecular Biology. </i> [[PubMed](https://www.ncbi.nlm.nih.gov/pubmed/29394092)]

## 2017

Jessica A. White, **Candace Haghighi**, Johanna Brunner, Marcus Estrada, Manjari Lal, and Dexiang Chen. Preformulation studies with <i> Escherichia coli </i> double mutant heat-labile toxin adjuvant for use in an oral vaccine. <i> Journal of Immunological Methods. </i> [[PubMed](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5703769/)]

## 2015

<i> Abstract: </i> Jason S. Debley, Stephen R. Reeves, Veronika Glukhova, Tessa Kolstad, Amelia Gallaher, **Candace Haghighi**, Dana Seyoum, and Richard G. James. Role of Follistatin-Like-3 (FSTL3) Secretion by Asthmatic Epithelial Cells in Regulating Lung Fibroblast Extracellular Matrix Expression and Fibroblast-to-Myofibroblast Transition.<i> American Journal of Respiratory and Critical Care Medicine. </i> [[ATSJournals](https://www.atsjournals.org/doi/abs/10.1164/ajrccm-conference.2015.191.1_MeetingAbstracts.A2642)] 

***

###**[TOP](#)**
Copyright 2018 Candace Haghighi

<br>
<br>
