<br>

## Resume

***

### EDUCATION
##### **Columbia University, Mailman School of Public Health**
+ MPH in Epidemiology/Biostatistics 
+ Graduate GPA: 3.9
+ *Graduate Thesis:* Examining the relation between immune gene mutations and chromosomally normal miscarriage.

##### **University of Washington, College Honors Program**
+ B.Sc. in Microbiology 
+ B.Sc. in Molecular/Cellular/Developmental Biology
+ Undergraduate GPA: 3.5
+ *Honors Undergraduate Thesis:* Used an inducible lentivirus shRNA system to knockdown genes of interest in airway epithelial cells and human lung fibroblasts to study the role of the epithelium in airway remodeling. 	

***

### WORK EXPERIENCE
##### **Columbia University Medical Center (New York, NY)**
+ *Data Analyst* 

##### **Project STAY (New York, NY)**
+ *Health Educator* 

##### **PATH (Seattle, WA)**
+ *Pre-Clinical Project Coordinator* 

+ *Laboratory Technician* 

##### **Vectr (Seattle, WA)**
+ *Co-Founder:* [Vectr](https://vectrapp.com/). 

***

### RESEARCH
##### **Dr. Jason Debley Lab | Seattle Children’s Research Institute, Center for Immunity and Immunotherapies**
+ *Research Assistant:* Explored potential aberrant epithelial-mesenchymal crosstalk in the asthmatic airway using acquired cells from human subjects. Performed a high volume of mammalian cell tissue culture. Assisted in the design, execution, and interpretation of experiments.

##### **Dr. Mary Lidstrom Lab | University of Washington, Department of Microbiology**
+ *Research Assistant:* Executed efficient lab practices around acquisition of usable microbial samples to study methane metabolism, analyzed microbial metabolic networks, and perfected general laboratory techniques.

##### **Dr. Georg Seelig Lab | University of Washington, Department of Electrical Engineering**
+ *Research Assistant:* Developed a non-directional expression vector to study the efficiency of microRNA biogenesis and microRNA regulatory dynamics; assisted in vector transfection in hES cells. 

***

### SKILLSET
Operations | Technical/Data | Languages
------------- | ------------- | -------------
Outlook | R | English
Word | SAS | Farsi
SharePoint | PRISM | Turkish (Elementary)
PowerPoint | Access | Spanish (Elementary)
MS Project | MySQL |
GitHub | Excel | 

***

###**[TOP](#)**
Copyright 2018 Candace Haghighi

<br>
<br>
